import type {
  User,
  Project,
  Team,
  RubricCriterion,
  AssignedProject,
  EventOverview,
  JudgeUser,
  JudgeAssignment,
  ProjectRankingResult,
  ProjectEvaluation,
} from '../types';

export const MOCK_USERS: Record<string, User> = {
  visitor: {
    id: 'usr_visitor',
    name: 'Guest Visitor',
    email: 'guest@example.com',
    role: 'visitor',
  },
  participant: {
    id: 'usr_p1',
    name: 'Alex Rivera',
    email: 'alex.rivera@example.com',
    role: 'participant',
    teamId: 'team_aurora',
  },
  judge: {
    id: 'usr_j1',
    name: 'Dr. Evelyn Vance',
    email: 'evelyn.vance@example.com',
    role: 'judge',
  },
  organizer: {
    id: 'usr_o1',
    name: 'Marcus Sterling',
    email: 'marcus.sterling@example.com',
    role: 'organizer',
  },
  admin: {
    id: 'usr_a1',
    name: 'Sarah Connor',
    email: 'sarah.connor@example.com',
    role: 'admin',
  },
};

export const MOCK_TEAMS: Team[] = [
  {
    id: 'team_aurora',
    name: 'Aurora Systems',
    inviteCode: 'AURORA-2026',
    projectId: 'proj_1',
    status: 'active',
    createdAt: '2026-09-20T10:00:00Z',
    members: [
      {
        id: 'usr_p1',
        name: 'Alex Rivera',
        email: 'alex.rivera@example.com',
        role: 'leader',
        joinedAt: '2026-09-20T10:00:00Z',
      },
      {
        id: 'usr_p2',
        name: 'Devon Lee',
        email: 'devon.lee@example.com',
        role: 'member',
        joinedAt: '2026-09-21T14:30:00Z',
      },
      {
        id: 'usr_p3',
        name: 'Priya Patel',
        email: 'priya.patel@example.com',
        role: 'member',
        joinedAt: '2026-09-22T09:15:00Z',
      },
    ],
  },
  {
    id: 'team_nexus',
    name: 'Nexus Dynamics',
    inviteCode: 'NEXUS-778',
    projectId: 'proj_2',
    status: 'active',
    createdAt: '2026-09-20T11:00:00Z',
    members: [
      {
        id: 'usr_p4',
        name: 'Liam Chen',
        email: 'liam.chen@example.com',
        role: 'leader',
        joinedAt: '2026-09-20T11:00:00Z',
      },
    ],
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj_1',
    title: 'Prometheus: Cloud-Native Systems Monitoring & Time Series Database',
    summary: 'Graduated CNCF monitoring system and time series database powering observability across Kubernetes and distributed architectures.',
    description: 'Prometheus collects and stores metrics as time series data, providing high-dimensional data model queries via PromQL, autonomous single-node server reliability, and real-time alerting.',
    track: 'Infrastructure',
    teamId: 'team_aurora',
    teamName: 'Aurora Systems',
    repositoryUrl: 'https://github.com/prometheus/prometheus',
    demoUrl: 'https://prometheus.io',
    submissionStatus: 'submitted',
    submittedAt: '2026-09-26T18:45:00Z',
    createdAt: '2026-09-21T09:00:00Z',
    updatedAt: '2026-09-26T18:45:00Z',
  },
  {
    id: 'proj_2',
    title: 'Excalidraw: Collaborative Virtual Hand-Drawn Whiteboard',
    summary: 'Virtual whiteboard for sketching hand-drawn like diagrams with end-to-end encryption and real-time multiplayer collaboration.',
    description: 'Excalidraw is a versatile web-based drawing tool built in React and TypeScript. Features infinite canvas rendering, SVG/PNG export, local storage persistence, and shareable collaboration links.',
    track: 'Developer Tools',
    teamId: 'team_nexus',
    teamName: 'Nexus Dynamics',
    repositoryUrl: 'https://github.com/excalidraw/excalidraw',
    demoUrl: 'https://excalidraw.com',
    submissionStatus: 'submitted',
    submittedAt: '2026-09-26T19:10:00Z',
    createdAt: '2026-09-21T11:30:00Z',
    updatedAt: '2026-09-26T19:10:00Z',
  },
  {
    id: 'proj_3',
    title: 'Trivy: Comprehensive Container & Cloud Security Vulnerability Scanner',
    summary: 'Fast and versatile security scanner detecting CVE vulnerabilities, misconfigurations, secrets, and SBOM licenses in container images and code repositories.',
    description: 'Trivy by Aqua Security scans container registries, virtual machine filesystems, and Kubernetes clusters. Evaluates package dependencies against authoritative vulnerability databases with instant CLI reporting.',
    track: 'Security',
    teamId: 'team_spectra',
    teamName: 'Spectra Lab',
    repositoryUrl: 'https://github.com/aquasecurity/trivy',
    demoUrl: 'https://trivy.dev',
    submissionStatus: 'submitted',
    submittedAt: '2026-09-26T20:00:00Z',
    createdAt: '2026-09-22T08:00:00Z',
    updatedAt: '2026-09-26T20:00:00Z',
  },
  {
    id: 'proj_4',
    title: 'Ollama: Local Large Language Model Execution & Serving Engine',
    summary: 'Get up and running with open-weights LLMs (Llama 3, Mistral, Gemma) locally on macOS, Linux, and Windows with hardware acceleration.',
    description: 'Ollama bundles model weights, configurations, and datasets into a unified Modelfile. Features a high-performance REST API, OpenAI-compatible completion endpoints, and optimized GPU inference routines.',
    track: 'AI & Data',
    teamId: 'team_voxel',
    teamName: 'VoxelFlow Collective',
    repositoryUrl: 'https://github.com/ollama/ollama',
    demoUrl: 'https://ollama.com',
    submissionStatus: 'submitted',
    submittedAt: '2026-09-26T21:15:00Z',
    createdAt: '2026-09-22T14:00:00Z',
    updatedAt: '2026-09-26T21:15:00Z',
  },
  {
    id: 'proj_5',
    title: 'Caddy Server: Enterprise-Grade Web Server with Automatic HTTPS',
    summary: "Lightweight, memory-safe, modular web server written in Go with built-in automatic TLS certificate generation and renewal via Let's Encrypt.",
    description: 'Caddy simplifies production web serving and reverse proxying with concise Caddyfiles, dynamic JSON configuration APIs, zero-downtime reloads, and HTTP/3 support out of the box.',
    track: 'Infrastructure',
    teamId: 'team_bytebridge',
    teamName: 'Kernel Crew',
    repositoryUrl: 'https://github.com/caddyserver/caddy',
    demoUrl: 'https://caddyserver.com',
    submissionStatus: 'under_review',
    submittedAt: '2026-09-26T22:00:00Z',
    createdAt: '2026-09-23T10:00:00Z',
    updatedAt: '2026-09-26T22:00:00Z',
  },
  {
    id: 'proj_6',
    title: 'HTTPie: Modern Human-Friendly Command-Line & Web HTTP Client',
    summary: 'User-friendly CLI and API testing tool with JSON syntax highlighting, persistent sessions, formatted terminal output, and intuitive syntax.',
    description: 'HTTPie is designed for seamless debugging and interaction with HTTP services. Features simple headers, effortless file uploads, SSL support, and an interactive web playground for modern API workflows.',
    track: 'Developer Tools',
    teamId: 'team_sentinel',
    teamName: 'Sentinel Systems',
    repositoryUrl: 'https://github.com/httpie/cli',
    demoUrl: 'https://httpie.io',
    submissionStatus: 'submitted',
    submittedAt: '2026-09-26T22:30:00Z',
    createdAt: '2026-09-23T16:00:00Z',
    updatedAt: '2026-09-26T22:30:00Z',
  },
];

export const MOCK_RUBRIC_CRITERIA: RubricCriterion[] = [
  {
    id: 'crit_tech_execution',
    name: 'Technical Execution & Architecture',
    description: 'Depth of engineering complexity, code quality, robustness, and architectural soundness.',
    weight: 35,
    maxScore: 10,
  },
  {
    id: 'crit_originality',
    name: 'Originality & Technical Innovation',
    description: 'Novelty of approach, uniqueness of the problem solved, and creative problem solving.',
    weight: 25,
    maxScore: 10,
  },
  {
    id: 'crit_completeness',
    name: 'Completeness & Functionality',
    description: 'Degree to which the core technical prototype works, edge cases handled, and demo reliability.',
    weight: 25,
    maxScore: 10,
  },
  {
    id: 'crit_presentation',
    name: 'Clarity & Engineering Presentation',
    description: 'Quality of technical documentation, architectural diagrams, and clarity of the demo.',
    weight: 15,
    maxScore: 10,
  },
];

export const MOCK_EVALUATIONS: Record<string, ProjectEvaluation> = {
  'usr_j1_proj_1': {
    projectId: 'proj_1',
    judgeId: 'usr_j1',
    submitted: true,
    submittedAt: '2026-09-27T08:30:00Z',
    scores: [
      { criterionId: 'crit_tech_execution', score: 9, comment: 'Clean eBPF implementation with minimal overhead.' },
      { criterionId: 'crit_originality', score: 8, comment: 'Solid approach to edge monitoring.' },
      { criterionId: 'crit_completeness', score: 9, comment: 'All advertised metrics collection works end-to-end.' },
      { criterionId: 'crit_presentation', score: 8, comment: 'Well structured readme and benchmark logs.' },
    ],
    generalFeedback: 'Exceptional engineering discipline for a 72-hour hackathon build.',
  },
};

export const MOCK_ASSIGNED_PROJECTS: AssignedProject[] = [
  {
    assignmentId: 'asgn_1',
    project: MOCK_PROJECTS[0],
    status: 'completed',
    assignedAt: '2026-09-27T02:00:00Z',
    evaluatedAt: '2026-09-27T08:30:00Z',
    currentScores: MOCK_EVALUATIONS['usr_j1_proj_1'].scores,
    feedback: MOCK_EVALUATIONS['usr_j1_proj_1'].generalFeedback,
  },
  {
    assignmentId: 'asgn_2',
    project: MOCK_PROJECTS[1],
    status: 'in_progress',
    assignedAt: '2026-09-27T02:00:00Z',
    currentScores: [
      { criterionId: 'crit_tech_execution', score: 8, comment: 'Persistent tree is well designed.' },
    ],
  },
  {
    assignmentId: 'asgn_3',
    project: MOCK_PROJECTS[2],
    status: 'pending',
    assignedAt: '2026-09-27T02:00:00Z',
  },
  {
    assignmentId: 'asgn_4',
    project: MOCK_PROJECTS[4],
    status: 'pending',
    assignedAt: '2026-09-27T02:00:00Z',
  },
];

export const MOCK_EVENT_OVERVIEW: EventOverview = {
  eventName: 'DOGFOOD 2026 Hackathon',
  tagline: 'Engineering the next generation of developer infrastructure',
  totalProjects: 6,
  submittedProjects: 5,
  totalJudges: 8,
  activeJudges: 7,
  assignmentsTotal: 24,
  assignmentsCompleted: 14,
  judgingProgress: 58.3,
  submissionDeadline: '2026-09-27T23:59:59Z',
  submissionOpen: true,
};

export const MOCK_JUDGES: JudgeUser[] = [
  {
    id: 'usr_j1',
    name: 'Dr. Evelyn Vance',
    email: 'evelyn.vance@example.com',
    role: 'judge',
    assignedTracks: ['Infrastructure', 'Security'],
    assignedProjectsCount: 4,
    completedReviewsCount: 1,
    status: 'active',
  },
  {
    id: 'usr_j2',
    name: 'Arthur Pendelton',
    email: 'arthur.pendelton@example.com',
    role: 'judge',
    assignedTracks: ['Developer Tools', 'Infrastructure'],
    assignedProjectsCount: 4,
    completedReviewsCount: 3,
    status: 'active',
  },
  {
    id: 'usr_j3',
    name: 'Rin Takahashi',
    email: 'rin.takahashi@example.com',
    role: 'judge',
    assignedTracks: ['AI & Data'],
    assignedProjectsCount: 3,
    completedReviewsCount: 3,
    status: 'active',
  },
  {
    id: 'usr_j4',
    name: 'Kofi Mensah',
    email: 'kofi.mensah@example.com',
    role: 'judge',
    assignedTracks: ['Security'],
    assignedProjectsCount: 4,
    completedReviewsCount: 2,
    status: 'active',
  },
];

export const MOCK_ASSIGNMENTS: JudgeAssignment[] = [
  {
    id: 'asgn_1',
    judgeId: 'usr_j1',
    judgeName: 'Dr. Evelyn Vance',
    projectId: 'proj_1',
    projectTitle: 'KubePulse: Lightweight Distributed Telemetry for Edge Nodes',
    track: 'Infrastructure',
    status: 'completed',
    assignedAt: '2026-09-27T02:00:00Z',
  },
  {
    id: 'asgn_2',
    judgeId: 'usr_j1',
    judgeName: 'Dr. Evelyn Vance',
    projectId: 'proj_2',
    projectTitle: 'AegisDB: Deterministic Time-Travel Database Engine',
    track: 'Developer Tools',
    status: 'assigned',
    assignedAt: '2026-09-27T02:00:00Z',
  },
  {
    id: 'asgn_3',
    judgeId: 'usr_j2',
    judgeName: 'Arthur Pendelton',
    projectId: 'proj_2',
    projectTitle: 'AegisDB: Deterministic Time-Travel Database Engine',
    track: 'Developer Tools',
    status: 'completed',
    assignedAt: '2026-09-27T02:00:00Z',
  },
  {
    id: 'asgn_4',
    judgeId: 'usr_j3',
    judgeName: 'Rin Takahashi',
    projectId: 'proj_4',
    projectTitle: 'VoxelFlow: Streaming 3D Gaussian Splatting Renderer',
    track: 'AI & Data',
    status: 'completed',
    assignedAt: '2026-09-27T02:00:00Z',
  },
];

export const MOCK_RANKING_RESULTS: ProjectRankingResult[] = [
  {
    rank: 1,
    projectId: 'proj_1',
    projectTitle: 'KubePulse: Lightweight Distributed Telemetry for Edge Nodes',
    teamName: 'Aurora Systems',
    track: 'Infrastructure',
    averageScore: 8.75,
    totalEvaluations: 3,
    reviewStatus: 'completed',
  },
  {
    rank: 2,
    projectId: 'proj_2',
    projectTitle: 'AegisDB: Deterministic Time-Travel Database Engine',
    teamName: 'Nexus Dynamics',
    track: 'Developer Tools',
    averageScore: 8.40,
    totalEvaluations: 2,
    reviewStatus: 'completed',
  },
  {
    rank: 3,
    projectId: 'proj_4',
    projectTitle: 'VoxelFlow: Streaming 3D Gaussian Splatting Renderer',
    teamName: 'VoxelFlow Collective',
    track: 'AI & Data',
    averageScore: 8.10,
    totalEvaluations: 3,
    reviewStatus: 'completed',
  },
  {
    rank: 4,
    projectId: 'proj_3',
    projectTitle: 'SpectraTrace: Autonomous API Vulnerability Fuzzer',
    teamName: 'Spectra Lab',
    track: 'Security',
    averageScore: 7.95,
    totalEvaluations: 2,
    reviewStatus: 'partial',
  },
  {
    rank: 5,
    projectId: 'proj_5',
    projectTitle: 'ByteBridge: Zero-Copy IPC Transport for Heterogeneous Subsystems',
    teamName: 'Kernel Crew',
    track: 'Infrastructure',
    averageScore: 7.50,
    totalEvaluations: 1,
    reviewStatus: 'partial',
  },
];
